
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.4]
    steps:
      - uses: actions/checkout@master
      - name: install, build, and test
        run: |
          yarn install
          yarn add prettier sass
          yarn pretty
          yarn build
        env:
          CI: true
      - name: Deploy to production
        uses: awb-pw/deploy-to-github-pages-action@1.1.1
        env:
          AUTHOR: ayannw
          BUILD_PATH: public
          GITHUB_PAGE_NAME: ayannw.github.io
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          USERNAME: awibox